apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cais-api-tls
spec:
  secretName: cais-api-ssl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - cais-api.dair.cloud