apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cais-camunda-ssl
spec:
  secretName: cais-camunda-ssl-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - cais-camunda.dair.cloud