server:
  port: ${PORT:8080}
  error:
    include-message: always
---
spring:
  datasource:
    url: jdbc:postgresql://headless-cms-db.cluster-cudjfioirmo2.us-east-1.rds.amazonaws.com/case_manager
    username: postgres
    password: headless-cms-db
    initialization-mode: always
    platform: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
