FROM --platform=linux/amd64 openjdk:21
COPY target/cais-position-service-0.0.1-SNAPSHOT.jar cais-position-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/cais-position-service-0.0.1-SNAPSHOT.jar"]